"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["main.py"]
DATA_FILES = []
OPTIONS = {
    "iconfile": "icon.icns",
    "packages": ["PIL", "pillow_avif", "pillow_heif", "PyQt6"],
}

setup(
    app=APP,
    name="ImageResizer",
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
