
name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build
      run: |
        python setup.py py2app
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: dist/ImageResizer.app
